package main

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	defaultBaseURL     = "https://api.deepseek.com"
	defaultModel       = "deepseek-v4-flash"
	defaultTemperature = 0.7
	defaultTimeout     = 60 * time.Second
)

type chatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type thinkingConfig struct {
	Type string `json:"type"`
}

type responseFormat struct {
	Type string `json:"type"`
}

type chatRequest struct {
	Model          string          `json:"model"`
	Messages       []chatMessage   `json:"messages"`
	Temperature    float64         `json:"temperature,omitempty"`
	MaxTokens      int             `json:"max_tokens,omitempty"`
	Thinking       *thinkingConfig `json:"thinking,omitempty"`
	ResponseFormat *responseFormat `json:"response_format,omitempty"`
	Stop           string          `json:"stop,omitempty"`
}

type chatResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage *struct {
		PromptTokens     int `json:"prompt_tokens"`
		CompletionTokens int `json:"completion_tokens"`
		TotalTokens      int `json:"total_tokens"`
	} `json:"usage,omitempty"`
}

type apiError struct {
	Error any `json:"error"`
}

type config struct {
	APIKey         string
	BaseURL        string
	Model          string
	Prompt         string
	Timeout        time.Duration
	Temperature    float64
	MaxTokens      int
	ResponseFormat bool
	StopSequence   string
}

func main() {
	cfg, err := readConfig(os.Args[1:], os.Stdin)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Ошибка:", err)
		os.Exit(1)
	}

	answer, usage, err := requestCompletion(context.Background(), http.DefaultClient, cfg)
	if err != nil {
		fmt.Fprintln(os.Stderr, "Ошибка:", err)
		os.Exit(1)
	}

	if cfg.ResponseFormat {
		validated, err := validateMovieReviewJSON(answer, cfg.StopSequence)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Ошибка: controlled JSON response is invalid:", err)
			os.Exit(1)
		}
		fmt.Println(validated)
	} else {
		fmt.Println(answer)
	}
	if usage != nil {
		fmt.Fprintf(os.Stderr, "\nTokens: prompt=%d completion=%d total=%d\n", usage.PromptTokens, usage.CompletionTokens, usage.TotalTokens)
	}
}

func readConfig(args []string, stdin io.Reader) (config, error) {
	if err := loadDotEnv(".env"); err != nil {
		return config{}, err
	}

	flags := flag.NewFlagSet("deepseek-cli", flag.ContinueOnError)
	flags.SetOutput(io.Discard)

	var cfg config
	flags.StringVar(&cfg.Prompt, "prompt", "", "prompt to send to DeepSeek")
	flags.BoolVar(&cfg.ResponseFormat, "response-format", false, "return a validated movie-review JSON response")
	flags.IntVar(&cfg.MaxTokens, "max-tokens", 0, "maximum number of tokens generated by DeepSeek; omit or keep 0 to use API default")
	flags.StringVar(&cfg.StopSequence, "stop", "", "stop sequence to send to DeepSeek")

	if err := flags.Parse(args); err != nil {
		return config{}, err
	}
	if cfg.MaxTokens < 0 {
		return config{}, errors.New("значение -max-tokens не может быть отрицательным")
	}

	cfg.APIKey = strings.TrimSpace(os.Getenv("DEEPSEEK_API_KEY"))
	if cfg.APIKey == "" {
		return config{}, errors.New("переменная окружения DEEPSEEK_API_KEY не задана")
	}

	if cfg.Prompt == "" {
		if shouldReadStdin(stdin) {
			piped, err := io.ReadAll(stdin)
			if err != nil {
				return config{}, fmt.Errorf("не удалось прочитать stdin: %w", err)
			}
			cfg.Prompt = strings.TrimSpace(string(piped))
		}
	}

	if cfg.Prompt == "" {
		return config{}, errors.New("передайте текст через -prompt или stdin")
	}

	cfg.Model = defaultModel
	cfg.BaseURL = strings.TrimRight(defaultBaseURL, "/")
	cfg.Timeout = defaultTimeout
	cfg.Temperature = defaultTemperature
	return cfg, nil
}

func requestCompletion(ctx context.Context, client *http.Client, cfg config) (string, *struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}, error) {
	ctx, cancel := context.WithTimeout(ctx, cfg.Timeout)
	defer cancel()

	reqBody := chatRequest{
		Model:       cfg.Model,
		Messages:    buildMessages(cfg),
		Temperature: cfg.Temperature,
		MaxTokens:   cfg.MaxTokens,
		Thinking:    &thinkingConfig{Type: "disabled"},
	}
	if cfg.ResponseFormat {
		reqBody.ResponseFormat = &responseFormat{Type: "json_object"}
	}
	if cfg.StopSequence != "" {
		reqBody.Stop = cfg.StopSequence
	}

	payload, err := json.Marshal(reqBody)
	if err != nil {
		return "", nil, fmt.Errorf("не удалось собрать JSON-запрос: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, cfg.BaseURL+"/chat/completions", bytes.NewReader(payload))
	if err != nil {
		return "", nil, fmt.Errorf("не удалось создать HTTP-запрос: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+cfg.APIKey)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return "", nil, fmt.Errorf("DeepSeek API недоступен: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", nil, fmt.Errorf("не удалось прочитать ответ DeepSeek: %w", err)
	}

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return "", nil, fmt.Errorf("DeepSeek API вернул HTTP %d: %s", resp.StatusCode, formatAPIError(respBody))
	}

	var decoded chatResponse
	if err := json.Unmarshal(respBody, &decoded); err != nil {
		return "", nil, fmt.Errorf("не удалось разобрать JSON-ответ DeepSeek: %w", err)
	}
	if len(decoded.Choices) == 0 {
		return "", nil, errors.New("DeepSeek API вернул ответ без choices")
	}

	answer := strings.TrimSpace(decoded.Choices[0].Message.Content)
	if answer == "" {
		return "", nil, errors.New("DeepSeek API вернул пустой ответ")
	}

	return answer, decoded.Usage, nil
}

func buildMessages(cfg config) []chatMessage {
	systemPrompt := "You are a helpful assistant."
	if cfg.ResponseFormat {
		systemPrompt = movieReviewSystemInstruction(cfg.StopSequence)
	}

	userPrompt := strings.TrimSpace(cfg.Prompt)

	return []chatMessage{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: userPrompt},
	}
}

func movieReviewSystemInstruction(stopSequence string) string {
	instruction := `Ты отвечаешь только валидным JSON, без markdown, без code fence и без пояснений вне JSON.
Верни объект JSON строго по этой схеме:
{
  "type": "object",
  "additionalProperties": false,
  "required": [
    "is_movie_review",
    "title",
    "release_date",
    "rating",
    "short_description",
    "actors",
    "error"
  ],
  "properties": {
    "is_movie_review": {"type": "boolean"},
    "title": {"type": ["string", "null"]},
    "release_date": {"type": ["string", "null"]},
    "rating": {"type": ["string", "null"]},
    "short_description": {"type": ["string", "null"]},
    "actors": {"type": "array", "items": {"type": "string"}},
    "error": {"type": ["string", "null"]}
  }
}

Если запрос пользователя является запросом на рецензию фильма, заполни:
{
  "is_movie_review": true,
  "title": "...",
  "release_date": "...",
  "rating": "...",
  "short_description": "...",
  "actors": ["..."],
  "error": null
}

Если запрос пользователя не является запросом на рецензию фильма, верни ровно такую структуру:
{
  "is_movie_review": false,
  "title": null,
  "release_date": null,
  "rating": null,
  "short_description": "Запрос пользователя не является запросом на рецензию фильма.",
  "actors": [],
  "error": null
}`

	if stopSequence != "" {
		instruction += "\n\nПосле полностью закрытого JSON-объекта выведи stop sequence " + strconv.Quote(stopSequence) + ". Не включай этот маркер внутрь JSON-строк и не выводи ничего после него."
	}
	return instruction
}

type movieReview struct {
	IsMovieReview    bool     `json:"is_movie_review"`
	Title            *string  `json:"title"`
	ReleaseDate      *string  `json:"release_date"`
	Rating           *string  `json:"rating"`
	ShortDescription *string  `json:"short_description"`
	Actors           []string `json:"actors"`
	Error            *string  `json:"error"`
}

func validateMovieReviewJSON(raw, stopSequence string) (string, error) {
	cleaned := stripTrailingStopSequence(strings.TrimSpace(raw), stopSequence)

	var fields map[string]json.RawMessage
	if err := json.Unmarshal([]byte(cleaned), &fields); err != nil {
		return "", fmt.Errorf("ответ не является валидным JSON: %w", err)
	}

	requiredFields := []string{
		"is_movie_review",
		"title",
		"release_date",
		"rating",
		"short_description",
		"actors",
		"error",
	}
	required := make(map[string]struct{}, len(requiredFields))
	for _, field := range requiredFields {
		required[field] = struct{}{}
		if _, ok := fields[field]; !ok {
			return "", fmt.Errorf("нет обязательного поля %q", field)
		}
	}
	for field := range fields {
		if _, ok := required[field]; !ok {
			return "", fmt.Errorf("лишнее поле %q", field)
		}
	}

	var parsed movieReview
	if err := json.Unmarshal([]byte(cleaned), &parsed); err != nil {
		return "", fmt.Errorf("JSON не соответствует ожидаемым типам: %w", err)
	}
	if parsed.Actors == nil {
		return "", errors.New(`поле "actors" должно быть массивом, а не null`)
	}

	if parsed.IsMovieReview {
		if isEmptyStringPointer(parsed.Title) {
			return "", errors.New(`для рецензии фильма поле "title" должно быть непустой строкой`)
		}
		if isEmptyStringPointer(parsed.ReleaseDate) {
			return "", errors.New(`для рецензии фильма поле "release_date" должно быть непустой строкой`)
		}
		if isEmptyStringPointer(parsed.Rating) {
			return "", errors.New(`для рецензии фильма поле "rating" должно быть непустой строкой`)
		}
		if isEmptyStringPointer(parsed.ShortDescription) {
			return "", errors.New(`для рецензии фильма поле "short_description" должно быть непустой строкой`)
		}
	} else {
		if parsed.Title != nil || parsed.ReleaseDate != nil || parsed.Rating != nil {
			return "", errors.New(`для не-фильмового запроса поля "title", "release_date" и "rating" должны быть null`)
		}
		if parsed.ShortDescription == nil || *parsed.ShortDescription != "Запрос пользователя не является запросом на рецензию фильма." {
			return "", errors.New(`для не-фильмового запроса поле "short_description" должно содержать стандартное сообщение`)
		}
		if len(parsed.Actors) != 0 {
			return "", errors.New(`для не-фильмового запроса поле "actors" должно быть пустым массивом`)
		}
	}

	normalized, err := json.MarshalIndent(parsed, "", "  ")
	if err != nil {
		return "", fmt.Errorf("не удалось нормализовать JSON: %w", err)
	}
	return string(normalized), nil
}

func stripTrailingStopSequence(answer, stopSequence string) string {
	if stopSequence == "" {
		return answer
	}
	return strings.TrimSpace(strings.TrimSuffix(answer, stopSequence))
}

func isEmptyStringPointer(value *string) bool {
	return value == nil || strings.TrimSpace(*value) == ""
}

func formatAPIError(body []byte) string {
	var decoded apiError
	if err := json.Unmarshal(body, &decoded); err == nil && decoded.Error != nil {
		formatted, err := json.Marshal(decoded.Error)
		if err == nil {
			return string(formatted)
		}
	}

	text := strings.TrimSpace(string(body))
	if text == "" {
		return "empty response body"
	}
	return text
}

func loadDotEnv(path string) error {
	file, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("не удалось открыть %s: %w", path, err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for lineNumber := 1; scanner.Scan(); lineNumber++ {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		key, value, ok := strings.Cut(line, "=")
		if !ok {
			return fmt.Errorf("некорректная строка %d в %s", lineNumber, path)
		}

		key = strings.TrimSpace(key)
		value = strings.Trim(strings.TrimSpace(value), `"'`)
		if key == "" {
			return fmt.Errorf("пустой ключ в строке %d файла %s", lineNumber, path)
		}
		if _, exists := os.LookupEnv(key); !exists {
			if err := os.Setenv(key, value); err != nil {
				return fmt.Errorf("не удалось установить %s из %s: %w", key, path, err)
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("не удалось прочитать %s: %w", path, err)
	}
	return nil
}

func shouldReadStdin(stdin io.Reader) bool {
	file, ok := stdin.(*os.File)
	if !ok {
		return true
	}

	info, err := file.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice == 0
}
