package document

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadSupportedDocumentsAndFilterForbiddenPaths(t *testing.T) {
	root := t.TempDir()
	write := func(relative, text string) {
		t.Helper()
		path := filepath.Join(root, relative)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("README.md", "# Пример\n\nСодержательный текст.")
	write("notes.txt", "one two\nthree")
	write("main.go", "package sample\n\nfunc main() {}\n")
	write("image.png", "not really an image")
	write(".env", "SECRET=value")
	write("vendor/ignored.go", "package ignored")
	write("artifacts/result.txt", "generated")
	write("build/generated.md", "generated")
	write("code_generated.go", "package ignored")
	write("auto.pb.go", "// Code generated by protoc. DO NOT EDIT.\npackage ignored")
	if err := os.WriteFile(filepath.Join(root, "binary.txt"), []byte{0xff, 0x00, 0x01}, 0o644); err != nil {
		t.Fatal(err)
	}

	docs, err := Load([]string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(docs) != 3 {
		t.Fatalf("got %d documents, want 3: %#v", len(docs), docs)
	}
	for _, doc := range docs {
		if strings.Contains(doc.Source, "vendor") || strings.Contains(doc.Source, "artifacts") || doc.SHA256 == "" {
			t.Fatalf("unexpected document: %#v", doc)
		}
		if doc.CharCount == 0 || doc.WordCount == 0 || doc.LineCount == 0 {
			t.Fatalf("missing statistics: %#v", doc)
		}
	}
}

func TestLoadPDFUsesExtractorAndRawHash(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "guide.pdf")
	if err := os.WriteFile(path, []byte("raw-pdf"), 0o644); err != nil {
		t.Fatal(err)
	}
	original := ExtractPDF
	ExtractPDF = func(got string) (string, int, error) {
		if got != path {
			t.Fatalf("extractor path = %q", got)
		}
		return "page one\fpage two", 2, nil
	}
	t.Cleanup(func() { ExtractPDF = original })
	docs, err := Load([]string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(docs) != 1 || docs[0].Type != "pdf" || docs[0].PageCount != 2 || docs[0].WordCount != 4 {
		t.Fatalf("unexpected PDF metadata: %#v", docs)
	}
	if docs[0].SHA256 != "35bcb50bd8b06cefb2ca45dd5ce0c1f6c4d2fadbb42ac2b725ddc5235a409643" {
		t.Fatalf("hash is not based on original bytes: %s", docs[0].SHA256)
	}
}

func TestManifestCorpusIDIsDeterministic(t *testing.T) {
	docs := []Document{{Source: "a.md", SHA256: "abc"}, {Source: "b.go", SHA256: "def"}}
	if CorpusID(docs) != CorpusID(docs) {
		t.Fatal("corpus ID is not deterministic")
	}
}
